import type { Metadata } from "next";
import { Chilanka, Caveat_Brush } from "next/font/google";
import "./globals.scss";
import Header from "./(components)/header/Header";
import { CSSProperties } from "react";
import { Footer } from "./(components)/footer/Footer";

const chilanka = Chilanka({
  subsets: ["latin"],
  weight: ["400"],
});

const caveat = Caveat_Brush({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "DJ Kat Avila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={""}
        style={
          {
            "--fontcb": caveat.style.fontFamily,
            "--fontch": chilanka.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
				<Footer/>
      </body>
    </html>
  );
}
